# -- Basic Settings ------------------------------------------
set -g prefix C-a
set -g escape-time 500
set -g history-limit 100000
set -g base-index 1
setw -g pane-base-index 1
set -g mouse on
set -g default-terminal "tmux-256color"
set -gw xterm-keys on
set-window-option -g mode-keys vi
set-option -g renumber-windows on
set -g extended-keys on
set -as terminal-features 'xterm*:extkeys'
set -as terminal-features 'tmux*:extkeys'
unbind -T copy-mode-vi MouseDragEnd1Pane

# -- Status Bar ---------------------------------------------
set -g status-position bottom
set -g status-interval 1
set -g status-left "#{session_name} "
set -g status-left-length 50
set -g status-right-length 50

# -- Key Bindings -------------------------------------------
bind-key x kill-pane
bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"
bind-key -n M-l next-window
bind-key -n M-h previous-window
bind-key "s" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""

set -g @tokyo-night-tmux_theme storm
set -g @tokyo-night-tmux_window_id_style none
set -g @tokyo-night-tmux_pane_id_style sub
set -g @tokyo-night-tmux_zoom_id_style super
set -g @tokyo-night-tmux_window_tidy_icons 0
set -g @tokyo-night-tmux_show_path 1
set -g @tokyo-night-tmux_path_format relative

# -- Plugins -----------------------------------------------
# Plugin manager
set -g @plugin 'tmux-plugins/tpm'

# Other plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin "janoamaral/tokyo-night-tmux"
#
# Keep this line at the very bottom of tmux.conf
run '~/.config/tmux/plugins/tpm/tpm'
