-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Dell Inc. DELL P2720D 22TXS03",
  mode = "2560x1440@59.95",
  position = "0x0",
  scale = 1.25,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Thermotrex Corporation TL140BDXP01-0",
  mode = "2560x1440@60.00",
  position = "465x1152",
  scale = 2,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "5", monitor = "desc:Thermotrex Corporation TL140BDXP01-0" })
