general {
  lock_cmd = hyprctl switchxkblayout asustek-computer-inc.-n-key-device-3 0 ; pidof hyprlock || hyprlock > ~/lock.log
  before_sleep_cmd = loginctl lock-session    # lock before suspend 
  after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

listener {
    timeout = 720
    on-timeout = hyprctl dispatch dpms off
    #on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 1200
    on-timeout = systemd-ac-power || systemctl suspend
}
