#! /bin/bash

PROFILE=$(asusctl profile -p | awk '{ print $4 }')

[[ "$PROFILE" = *LowPower* ]] && asusctl profile -P Balanced
[[ "$PROFILE" = *Balanced* ]] && asusctl profile -P Low-Power
[[ "$PROFILE" = *Performance* ]] && asusctl profile -P Balanced
notify -r profile_switch "$(asusctl profile -p | grep Active)"
exit 0
