#!/bin/bash
CURR_STATE=$(brightnessctl -d asus::kbd_backlight get)
OFF_BR=0

echo $CURR_STATE
if (($CURR_STATE > $OFF_BR)); then # turn off
  brightnessctl -d asus::kbd_backlight set 0
else # turn on
  brightnessctl -d asus::kbd_backlight set 1
fi
